global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets:
          - 'node:3000'
  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'worker:9100'
